[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = 'javascript'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = 'javascript'
